### ISSUE TITLE
Replace the game's ending notifications

### ISSUE THREAD

**Issue by ilyar** [fesic1/GameNew1#1]
Replace the game's ending notifications, currently implemented with alerts for both wins and losses, with a custom user interface using the `<canvas>` element. This task involves developing a graphical interface on the canvas that displays the game's outcome (win or loss) in a more visually appealing and integrated manner than the default alert boxes. The new interface should be designed to enhance the user experience by seamlessly integrating with the game's overall design and aesthetics.

**Comment by fesic1** [comment]
Ready. Thx
